# development tools
brew "nvim"
brew "npm"
brew "git-lfs"
# python
brew "pyenv"
brew "pipenv"
# clojure
brew "clojure-lsp"
brew "leiningen"
brew "clojure"
# ruby
brew "ruby"
# terminal tools
brew "coreutils"
brew "findutils"
brew "ripgrep"
brew "curl"
brew "wget"
brew "bat"
brew "fzf"
brew "jq"
brew "fd"
# beautiful terminal
brew "zsh"
# casks
cask "font-fira-code-nerd-font"
cask "emacs"
